services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tahicz\SymfonyStatusLoggerBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Tahicz\SymfonyStatusLoggerBundle\Repository\:
        resource: '../../Repository'
        tags: ['doctrine.repository_service']

    Tahicz\SymfonyStatusLoggerBundle\StatusExport\Model\ServiceStatus: ~
    Tahicz\SymfonyStatusLoggerBundle\StatusExport\StatusExport: ~

