services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tahicz\SymfonyStatusLoggerBundle\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
